//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jdMiniCS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("template.cs")]
        public string CSharpTemplate {
            get {
                return ((string)(this["CSharpTemplate"]));
            }
            set {
                this["CSharpTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system.dll\r\nsystem.xml.dll\r\nSystem.Data.dll\r\nSystem.Drawing.dll\r\nsystem.core.dll\r" +
            "\nSystem.Windows.Forms.dll")]
        public string UsingsExe {
            get {
                return ((string)(this["UsingsExe"]));
            }
            set {
                this["UsingsExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system.dll\r\nsystem.xml.dll\r\nSystem.Data.dll\r\nSystem.Drawing.dll\r\nsystem.core.dll\r" +
            "\nSystem.Windows.Forms.dll")]
        public string UsingsMem {
            get {
                return ((string)(this["UsingsMem"]));
            }
            set {
                this["UsingsMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/optimize")]
        public string CompilerOptionsExe {
            get {
                return ((string)(this["CompilerOptionsExe"]));
            }
            set {
                this["CompilerOptionsExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/t:library")]
        public string CompilerOptionsMem {
            get {
                return ((string)(this["CompilerOptionsMem"]));
            }
            set {
                this["CompilerOptionsMem"] = value;
            }
        }
    }
}
